name: puppet-master
version: 0.2.0
synopsis: A puppetry webserver 
license: MIT
github: eguahlak/puppetry
category: Fun

ghc-options: -Wall

dependencies:
  - aeson
  - base
  - binary
  - bytestring
  - concurrent-extra
  - free
  - http-types
  - monadplus
  - mtl
  - safe
  - scotty
  - serialport
  - text
  - unix
  - vector
  - wai
  - wai-app-static
  - wai-websockets
  - warp
  - websockets
  - containers
#  - scotty
#  - blaze-html

library:
  source-dirs: src/haskell-lib

executables:
  puppet-master:
    main: Main.hs
    source-dirs: src/haskell-app
    dependencies:
      - puppet-master
